<?php

namespace AppBundle\Repository;

/**
 * DailyscrumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailyscrumRepository extends \Doctrine\ORM\EntityRepository
{
}
