<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{

    public function myfindProject($title)

    {
        $qb = $this->getEntityManager()
            ->createQuery("select p from AppBundle:Meeting p Where p.projecttitle=:title")
            ->setParameter('title', $title);

        return $query = $qb->getResult();
    }

    public function count()
    {
        {
            $query =$this->getEntityManager()
                ->createQuery('SELECT COUNT(p.id) FROM AppBundle:Project p');
            return  $result = $query->getSingleScalarResult();
        }
    }

}
