<?php

namespace AppBundle\Repository;

/**
 * ReleasesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReleasesRepository extends \Doctrine\ORM\EntityRepository
{
}
