<?php

namespace AppBundle\Repository;

/**
 * RetrospectiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetrospectiveRepository extends \Doctrine\ORM\EntityRepository
{
}
