<?php

namespace AppBundle\Repository;

/**
 * SprintreviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SprintreviewRepository extends \Doctrine\ORM\EntityRepository
{
}
