<?php

namespace ProductBacklogBundle\Repository;

/**
 * ProductBacklogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductBacklogRepository extends \Doctrine\ORM\EntityRepository
{
}
