<?php

namespace ProductBacklogBundle\Repository;

/**
 * UserStoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStoryRepository extends \Doctrine\ORM\EntityRepository
{
	
	
	 public function tri()
    {


    }


   public function SERCHUS($idFeature)
    {
       // $query = $this->getEntityManager()->createQuery('select * from user_story')->getResult();

        $qb = $this->getEntityManager()
            ->createQuery("SELECT u FROM ProductBacklogBundle:UserStory u where u.idFeature=:idf ")
            ->setParameter('idf', $idFeature);

        return $query = $qb->getResult();



    }

    public function SERCHFT($idTheme)
    {
        // $query = $this->getEntityManager()->createQuery('select * from user_story')->getResult();

        $qb = $this->getEntityManager()
            ->createQuery("SELECT f FROM ProductBacklogBundle:Feature f where f.idTheme=:idt ")
            ->setParameter('idt', $idTheme);

        return $query = $qb->getResult();



    }



    public function SERCHTheme($idFeature)
    {
        // $query = $this->getEntityManager()->createQuery('select * from user_story')->getResult();

        $qb = $this->getEntityManager()
            ->createQuery("SELECT t FROM ProductBacklogBundle:Theme u where u.idFeature=:idf ")
            ->setParameter('idf', $idFeature);

        return $query = $qb->getResult();



    }

    public function alluser()
    {
        // $query = $this->getEntityManager()->createQuery('select * from user_story')->getResult();

        $query = $this->getDoctrine()->getEntityManager()
            ->createQuery(
                'SELECT u FROM AppBundle:User u WHERE u.roles LIKE :role'
            )->setParameter('role', '%"ROLE_SUPER_ADMIN"%'
            );
        $users = $query->getResult();


    }

}
